"""
Historical Brazilian club squads with real players linked to their eras.
Positions used: GK, CB, LB, RB, CDM, CM, CAM, LM, RM, LW, RW, ST
OVR scale (per user requirements):
  93-99: All-time legends (Pelé, Zico, Romário, Ronaldo, Garrincha, Rivaldo, Ronaldinho)
  80-92: Club legends / top stars
  65-79: Regular starters
  55-64: Substitutes
  >=50  : floor
"""

SQUADS = [
    # ---------- 1. SANTOS 1962 (Pelé / Coutinho) ----------
    {
        "club": "Santos",
        "year": 1962,
        "label": "Santos 1962",
        "color": "#000000",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Gilmar", "pos": ["GK"], "ovr": 90},
            {"name": "Lalá", "pos": ["RB", "CB"], "ovr": 70},
            {"name": "Mauro Ramos", "pos": ["CB"], "ovr": 87},
            {"name": "Calvet", "pos": ["CB"], "ovr": 75},
            {"name": "Dalmo", "pos": ["LB", "RB"], "ovr": 72},
            {"name": "Zito", "pos": ["CDM", "CM"], "ovr": 88},
            {"name": "Mengálvio", "pos": ["CM", "CAM"], "ovr": 82},
            {"name": "Lima", "pos": ["CM"], "ovr": 73},
            {"name": "Dorval", "pos": ["RW", "RM"], "ovr": 80},
            {"name": "Coutinho", "pos": ["ST", "CAM"], "ovr": 92},
            {"name": "Pelé", "pos": ["ST", "CAM", "LW"], "ovr": 99},
            {"name": "Pepe", "pos": ["LW", "ST"], "ovr": 89},
            {"name": "Mauro", "pos": ["CB"], "ovr": 66},
            {"name": "Geraldino", "pos": ["CM"], "ovr": 60},
        ],
    },
    # ---------- 2. SANTOS 1969 (Pelé / Carlos Alberto) ----------
    {
        "club": "Santos",
        "year": 1969,
        "label": "Santos 1969",
        "color": "#0A0A0A",
        "accent": "#F5F5F5",
        "players": [
            {"name": "Cláudio", "pos": ["GK"], "ovr": 78},
            {"name": "Carlos Alberto Torres", "pos": ["RB"], "ovr": 92},
            {"name": "Djalma Dias", "pos": ["CB"], "ovr": 78},
            {"name": "Ramos Delgado", "pos": ["CB"], "ovr": 77},
            {"name": "Rildo", "pos": ["LB"], "ovr": 78},
            {"name": "Clodoaldo", "pos": ["CDM", "CM"], "ovr": 87},
            {"name": "Negreiros", "pos": ["CM"], "ovr": 70},
            {"name": "Abel", "pos": ["CM", "CDM"], "ovr": 72},
            {"name": "Edu", "pos": ["LW", "ST"], "ovr": 86},
            {"name": "Toninho Guerreiro", "pos": ["ST"], "ovr": 81},
            {"name": "Pelé", "pos": ["ST", "CAM", "LW"], "ovr": 99},
            {"name": "Pepe", "pos": ["LW", "ST"], "ovr": 84},
            {"name": "Joel Camargo", "pos": ["CB"], "ovr": 70},
            {"name": "Marcos Aurélio", "pos": ["CM"], "ovr": 65},
        ],
    },
    # ---------- 3. FLAMENGO 1981 (Zico / Júnior / Mundial) ----------
    {
        "club": "Flamengo",
        "year": 1981,
        "label": "Flamengo 1981",
        "color": "#D40026",
        "accent": "#000000",
        "players": [
            {"name": "Raul", "pos": ["GK"], "ovr": 82},
            {"name": "Leandro", "pos": ["RB"], "ovr": 91},
            {"name": "Marinho", "pos": ["CB"], "ovr": 79},
            {"name": "Mozer", "pos": ["CB"], "ovr": 81},
            {"name": "Júnior", "pos": ["LB", "CM"], "ovr": 90},
            {"name": "Andrade", "pos": ["CDM", "CM"], "ovr": 84},
            {"name": "Adílio", "pos": ["CM", "CAM"], "ovr": 82},
            {"name": "Zico", "pos": ["CAM", "ST"], "ovr": 96},
            {"name": "Tita", "pos": ["RW", "ST", "RM"], "ovr": 80},
            {"name": "Nunes", "pos": ["ST"], "ovr": 84},
            {"name": "Lico", "pos": ["LW", "LM"], "ovr": 76},
            {"name": "Anselmo", "pos": ["CB", "CDM"], "ovr": 68},
            {"name": "Peu", "pos": ["RB"], "ovr": 64},
            {"name": "Baroninho", "pos": ["CM"], "ovr": 60},
        ],
    },
    # ---------- 4. GRÊMIO 1983 (Renato / Libertadores) ----------
    {
        "club": "Grêmio",
        "year": 1983,
        "label": "Grêmio 1983",
        "color": "#0E4DA4",
        "accent": "#000000",
        "players": [
            {"name": "Mazaropi", "pos": ["GK"], "ovr": 79},
            {"name": "Paulo Roberto", "pos": ["RB"], "ovr": 74},
            {"name": "Hugo De León", "pos": ["CB"], "ovr": 86},
            {"name": "Baidek", "pos": ["CB"], "ovr": 72},
            {"name": "China", "pos": ["LB"], "ovr": 70},
            {"name": "De Léon", "pos": ["CB"], "ovr": 75},
            {"name": "Osvaldo", "pos": ["CDM", "CM"], "ovr": 75},
            {"name": "Paulo Isidoro", "pos": ["CAM", "RW"], "ovr": 84},
            {"name": "Tarciso", "pos": ["CM", "CAM"], "ovr": 78},
            {"name": "Renato Gaúcho", "pos": ["RW", "ST", "RM"], "ovr": 88},
            {"name": "Caio", "pos": ["ST"], "ovr": 75},
            {"name": "César", "pos": ["LW", "ST"], "ovr": 72},
            {"name": "Mário Sérgio", "pos": ["CM"], "ovr": 76},
            {"name": "Ancheta", "pos": ["CB"], "ovr": 68},
        ],
    },
    # ---------- 5. SÃO PAULO 1992 (Raí / Cafu) ----------
    {
        "club": "São Paulo",
        "year": 1992,
        "label": "São Paulo 1992",
        "color": "#E2231A",
        "accent": "#000000",
        "players": [
            {"name": "Zetti", "pos": ["GK"], "ovr": 85},
            {"name": "Cafu", "pos": ["RB", "RM"], "ovr": 91},
            {"name": "Ronaldão", "pos": ["CB"], "ovr": 80},
            {"name": "Adílson", "pos": ["CB"], "ovr": 76},
            {"name": "Ivan", "pos": ["LB"], "ovr": 72},
            {"name": "Pintado", "pos": ["CDM", "CM"], "ovr": 78},
            {"name": "Toninho Cerezo", "pos": ["CM", "CDM"], "ovr": 86},
            {"name": "Raí", "pos": ["CAM", "ST"], "ovr": 92},
            {"name": "Müller", "pos": ["RW", "ST"], "ovr": 87},
            {"name": "Palhinha", "pos": ["ST"], "ovr": 82},
            {"name": "Macedo", "pos": ["LW", "LM"], "ovr": 70},
            {"name": "Vítor", "pos": ["CB"], "ovr": 66},
            {"name": "Dinho", "pos": ["CM"], "ovr": 70},
            {"name": "Catê", "pos": ["ST"], "ovr": 65},
        ],
    },
    # ---------- 6. SÃO PAULO 2005 (Rogério Ceni / Libertadores) ----------
    {
        "club": "São Paulo",
        "year": 2005,
        "label": "São Paulo 2005",
        "color": "#E2231A",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Rogério Ceni", "pos": ["GK"], "ovr": 90},
            {"name": "Cicinho", "pos": ["RB", "RM"], "ovr": 80},
            {"name": "Diego Lugano", "pos": ["CB"], "ovr": 85},
            {"name": "Fabão", "pos": ["CB"], "ovr": 76},
            {"name": "Júnior", "pos": ["LB"], "ovr": 74},
            {"name": "Mineiro", "pos": ["CDM", "CM"], "ovr": 81},
            {"name": "Josué", "pos": ["CDM", "CM"], "ovr": 78},
            {"name": "Danilo", "pos": ["CM", "CAM"], "ovr": 77},
            {"name": "Amoroso", "pos": ["ST"], "ovr": 84},
            {"name": "Luizão", "pos": ["ST"], "ovr": 80},
            {"name": "Aloísio", "pos": ["ST"], "ovr": 75},
            {"name": "Falcão", "pos": ["CAM", "ST"], "ovr": 76},
            {"name": "Renan", "pos": ["CB"], "ovr": 70},
            {"name": "Souza", "pos": ["CM"], "ovr": 68},
        ],
    },
    # ---------- 7. CRUZEIRO 2003 (Tríplice Coroa - Alex / Deivid) ----------
    {
        "club": "Cruzeiro",
        "year": 2003,
        "label": "Cruzeiro 2003",
        "color": "#1B4FA0",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Gomes", "pos": ["GK"], "ovr": 84},
            {"name": "Maicon", "pos": ["RB", "RM"], "ovr": 86},
            {"name": "Cris", "pos": ["CB"], "ovr": 82},
            {"name": "Edu Dracena", "pos": ["CB"], "ovr": 78},
            {"name": "Jorge Wagner", "pos": ["LB", "LM"], "ovr": 79},
            {"name": "Mineiro", "pos": ["CDM", "CM"], "ovr": 80},
            {"name": "Augusto Recife", "pos": ["CM"], "ovr": 75},
            {"name": "Alex", "pos": ["CAM", "ST"], "ovr": 90},
            {"name": "Ricardinho", "pos": ["CAM", "CM"], "ovr": 81},
            {"name": "Deivid", "pos": ["ST"], "ovr": 80},
            {"name": "Aristizábal", "pos": ["ST"], "ovr": 79},
            {"name": "Geovanni", "pos": ["CAM", "RW"], "ovr": 78},
            {"name": "Luisão", "pos": ["CB"], "ovr": 76},
            {"name": "Fabiano Eller", "pos": ["CB"], "ovr": 68},
        ],
    },
    # ---------- 8. VASCO 1998 (Romário / Edmundo) ----------
    {
        "club": "Vasco",
        "year": 1998,
        "label": "Vasco 1998",
        "color": "#000000",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Carlos Germano", "pos": ["GK"], "ovr": 82},
            {"name": "Felipe", "pos": ["RB"], "ovr": 76},
            {"name": "Mauro Galvão", "pos": ["CB"], "ovr": 84},
            {"name": "Odvan", "pos": ["CB"], "ovr": 76},
            {"name": "Pedrinho", "pos": ["LB", "LM"], "ovr": 75},
            {"name": "Nasa", "pos": ["CDM", "CM"], "ovr": 77},
            {"name": "Juninho Pernambucano", "pos": ["CAM", "CM"], "ovr": 88},
            {"name": "Ramon", "pos": ["CM"], "ovr": 70},
            {"name": "Donizete Pantera", "pos": ["RW", "ST"], "ovr": 80},
            {"name": "Romário", "pos": ["ST", "CAM"], "ovr": 97},
            {"name": "Edmundo", "pos": ["ST", "CAM"], "ovr": 90},
            {"name": "Luizão", "pos": ["ST"], "ovr": 78},
            {"name": "Galvão", "pos": ["CB"], "ovr": 65},
            {"name": "Beto", "pos": ["CM"], "ovr": 65},
        ],
    },
    # ---------- 9. VASCO 2000 (Mundial - Romário/Euller) ----------
    {
        "club": "Vasco",
        "year": 2000,
        "label": "Vasco 2000",
        "color": "#0A0A0A",
        "accent": "#E2231A",
        "players": [
            {"name": "Hélton", "pos": ["GK"], "ovr": 80},
            {"name": "Amaral", "pos": ["RB", "CB"], "ovr": 76},
            {"name": "Mauro Galvão", "pos": ["CB"], "ovr": 80},
            {"name": "Odvan", "pos": ["CB"], "ovr": 75},
            {"name": "Gilberto", "pos": ["LB", "LM"], "ovr": 78},
            {"name": "Juninho Pernambucano", "pos": ["CAM", "CM"], "ovr": 89},
            {"name": "Ramon", "pos": ["CM", "CDM"], "ovr": 72},
            {"name": "Pedrinho", "pos": ["LW", "LM"], "ovr": 80},
            {"name": "Euller", "pos": ["RW", "ST"], "ovr": 81},
            {"name": "Romário", "pos": ["ST", "CAM"], "ovr": 94},
            {"name": "Edmundo", "pos": ["ST", "CAM"], "ovr": 85},
            {"name": "Viola", "pos": ["ST"], "ovr": 72},
            {"name": "Marcelinho Carioca", "pos": ["LW", "CAM"], "ovr": 78},
            {"name": "Felipe", "pos": ["RB"], "ovr": 70},
        ],
    },
    # ---------- 10. CORINTHIANS 2012 (Libertadores/Mundial) ----------
    {
        "club": "Corinthians",
        "year": 2012,
        "label": "Corinthians 2012",
        "color": "#000000",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Cássio", "pos": ["GK"], "ovr": 89},
            {"name": "Alessandro", "pos": ["RB"], "ovr": 76},
            {"name": "Chicão", "pos": ["CB"], "ovr": 82},
            {"name": "Leandro Castán", "pos": ["CB"], "ovr": 84},
            {"name": "Fábio Santos", "pos": ["LB", "LM"], "ovr": 78},
            {"name": "Ralf", "pos": ["CDM"], "ovr": 80},
            {"name": "Paulinho", "pos": ["CM", "CDM"], "ovr": 86},
            {"name": "Douglas", "pos": ["CAM", "CM"], "ovr": 73},
            {"name": "Danilo", "pos": ["CAM", "CM"], "ovr": 79},
            {"name": "Jorge Henrique", "pos": ["RW", "RM"], "ovr": 74},
            {"name": "Emerson Sheik", "pos": ["ST", "RW"], "ovr": 81},
            {"name": "Liedson", "pos": ["ST"], "ovr": 76},
            {"name": "Romarinho", "pos": ["CAM", "ST"], "ovr": 70},
            {"name": "Guerrero", "pos": ["ST"], "ovr": 78},
        ],
    },
    # ---------- 11. PALMEIRAS 1999 (Libertadores - Alex / Marcos) ----------
    {
        "club": "Palmeiras",
        "year": 1999,
        "label": "Palmeiras 1999",
        "color": "#006437",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Marcos", "pos": ["GK"], "ovr": 89},
            {"name": "Arce", "pos": ["RB"], "ovr": 80},
            {"name": "Roque Júnior", "pos": ["CB"], "ovr": 84},
            {"name": "Júnior Baiano", "pos": ["CB"], "ovr": 82},
            {"name": "Júnior", "pos": ["LB"], "ovr": 75},
            {"name": "César Sampaio", "pos": ["CDM", "CM"], "ovr": 82},
            {"name": "Galeano", "pos": ["CM", "CAM"], "ovr": 79},
            {"name": "Rogério", "pos": ["CM"], "ovr": 73},
            {"name": "Alex", "pos": ["CAM", "ST"], "ovr": 86},
            {"name": "Evair", "pos": ["ST"], "ovr": 80},
            {"name": "Oséas", "pos": ["ST"], "ovr": 76},
            {"name": "Paulo Nunes", "pos": ["ST", "RW"], "ovr": 78},
            {"name": "Zinho", "pos": ["LM", "LW"], "ovr": 80},
            {"name": "Asprilla", "pos": ["ST", "CAM"], "ovr": 78},
        ],
    },
    # ---------- 12. PALMEIRAS 2021 (Bi Libertadores) ----------
    {
        "club": "Palmeiras",
        "year": 2021,
        "label": "Palmeiras 2021",
        "color": "#006B3F",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Weverton", "pos": ["GK"], "ovr": 84},
            {"name": "Marcos Rocha", "pos": ["RB"], "ovr": 76},
            {"name": "Gustavo Gómez", "pos": ["CB"], "ovr": 84},
            {"name": "Luan", "pos": ["CB"], "ovr": 76},
            {"name": "Piquerez", "pos": ["LB", "LM"], "ovr": 79},
            {"name": "Danilo", "pos": ["CDM", "CM"], "ovr": 80},
            {"name": "Zé Rafael", "pos": ["CM", "CAM"], "ovr": 77},
            {"name": "Raphael Veiga", "pos": ["CAM", "CM"], "ovr": 85},
            {"name": "Dudu", "pos": ["LW", "CAM", "LM"], "ovr": 82},
            {"name": "Rony", "pos": ["ST", "RW"], "ovr": 80},
            {"name": "Deyverson", "pos": ["ST"], "ovr": 73},
            {"name": "Gustavo Scarpa", "pos": ["CAM", "LW"], "ovr": 79},
            {"name": "Felipe Melo", "pos": ["CDM", "CB"], "ovr": 73},
            {"name": "Wesley", "pos": ["RW", "LW"], "ovr": 68},
        ],
    },
    # ---------- 13. INTERNACIONAL 2006 (Libertadores/Mundial) ----------
    {
        "club": "Internacional",
        "year": 2006,
        "label": "Internacional 2006",
        "color": "#E2231A",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Clemer", "pos": ["GK"], "ovr": 80},
            {"name": "Ceará", "pos": ["RB"], "ovr": 77},
            {"name": "Fabiano Eller", "pos": ["CB"], "ovr": 75},
            {"name": "Índio", "pos": ["CB"], "ovr": 80},
            {"name": "Wellington Monteiro", "pos": ["LB"], "ovr": 72},
            {"name": "Edinho", "pos": ["CDM", "CM"], "ovr": 75},
            {"name": "Wilson", "pos": ["CDM"], "ovr": 73},
            {"name": "Perdigão", "pos": ["CM"], "ovr": 70},
            {"name": "Iarley", "pos": ["CAM", "ST"], "ovr": 80},
            {"name": "Rafael Sóbis", "pos": ["ST", "CAM"], "ovr": 79},
            {"name": "Fernandão", "pos": ["ST"], "ovr": 82},
            {"name": "Alexandre Pato", "pos": ["ST"], "ovr": 78},
            {"name": "Adriano Gabiru", "pos": ["LW", "ST"], "ovr": 72},
            {"name": "Tinga", "pos": ["CM", "CDM"], "ovr": 76},
        ],
    },
    # ---------- 14. ATLÉTICO-MG 2013 (Ronaldinho - Libertadores) ----------
    {
        "club": "Atlético-MG",
        "year": 2013,
        "label": "Atlético-MG 2013",
        "color": "#000000",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Victor", "pos": ["GK"], "ovr": 87},
            {"name": "Marcos Rocha", "pos": ["RB", "RM"], "ovr": 78},
            {"name": "Réver", "pos": ["CB"], "ovr": 82},
            {"name": "Leonardo Silva", "pos": ["CB"], "ovr": 80},
            {"name": "Júnior César", "pos": ["LB"], "ovr": 73},
            {"name": "Pierre", "pos": ["CDM"], "ovr": 77},
            {"name": "Leandro Donizete", "pos": ["CDM", "CM"], "ovr": 76},
            {"name": "Ronaldinho Gaúcho", "pos": ["CAM", "LW"], "ovr": 91},
            {"name": "Bernard", "pos": ["LW", "RW", "CAM"], "ovr": 82},
            {"name": "Diego Tardelli", "pos": ["ST", "CAM"], "ovr": 83},
            {"name": "Jô", "pos": ["ST"], "ovr": 80},
            {"name": "Luan", "pos": ["CAM", "ST"], "ovr": 74},
            {"name": "Richarlyson", "pos": ["LB", "LM"], "ovr": 70},
            {"name": "Rosinei", "pos": ["RW", "RM"], "ovr": 66},
        ],
    },
    # ---------- 15. BOTAFOGO 1995 (Túlio Maravilha) ----------
    {
        "club": "Botafogo",
        "year": 1995,
        "label": "Botafogo 1995",
        "color": "#000000",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Wágner", "pos": ["GK"], "ovr": 79},
            {"name": "Gonçalves", "pos": ["RB"], "ovr": 75},
            {"name": "Mauro Galvão", "pos": ["CB"], "ovr": 83},
            {"name": "Wilson Gottardo", "pos": ["CB"], "ovr": 75},
            {"name": "Luís Carlos", "pos": ["LB"], "ovr": 72},
            {"name": "Cláudio Adão", "pos": ["CDM", "CM"], "ovr": 73},
            {"name": "Donizete", "pos": ["CAM", "CM"], "ovr": 81},
            {"name": "Sinval", "pos": ["CM"], "ovr": 73},
            {"name": "Túlio Maravilha", "pos": ["ST", "CAM"], "ovr": 85},
            {"name": "Sérgio Manoel", "pos": ["LW", "LM"], "ovr": 74},
            {"name": "Vladimir", "pos": ["RW", "RM"], "ovr": 71},
            {"name": "Caio", "pos": ["ST"], "ovr": 70},
            {"name": "Gilson", "pos": ["CB"], "ovr": 65},
            {"name": "Marcelo Tavares", "pos": ["CDM"], "ovr": 65},
        ],
    },
    # ---------- 16. FLUMINENSE 1984 (Tricampeão - Assis/Romerito) ----------
    {
        "club": "Fluminense",
        "year": 1984,
        "label": "Fluminense 1984",
        "color": "#7A1F2B",
        "accent": "#1B6B43",
        "players": [
            {"name": "Paulo Vítor", "pos": ["GK"], "ovr": 82},
            {"name": "Aldo", "pos": ["RB"], "ovr": 73},
            {"name": "Edinho", "pos": ["CB"], "ovr": 83},
            {"name": "Duílio", "pos": ["CB"], "ovr": 75},
            {"name": "Branco", "pos": ["LB"], "ovr": 86},
            {"name": "Tato", "pos": ["CDM", "CM"], "ovr": 78},
            {"name": "Paulo César Carpegiani", "pos": ["CM"], "ovr": 70},
            {"name": "Assis", "pos": ["CAM", "ST"], "ovr": 82},
            {"name": "Romerito", "pos": ["CAM", "RW"], "ovr": 84},
            {"name": "Washington", "pos": ["ST"], "ovr": 78},
            {"name": "Délei", "pos": ["LW", "LM"], "ovr": 72},
            {"name": "Vivinho", "pos": ["CM", "CAM"], "ovr": 70},
            {"name": "Leomir", "pos": ["RB"], "ovr": 65},
            {"name": "Ivan", "pos": ["CB"], "ovr": 64},
        ],
    },
    # ---------- 17. GRÊMIO 1995 (Libertadores - Jardel/Roger) ----------
    {
        "club": "Grêmio",
        "year": 1995,
        "label": "Grêmio 1995",
        "color": "#0E4DA4",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Danrlei", "pos": ["GK"], "ovr": 83},
            {"name": "Arce", "pos": ["RB"], "ovr": 80},
            {"name": "Adílson", "pos": ["CB"], "ovr": 78},
            {"name": "Rivarola", "pos": ["CB"], "ovr": 76},
            {"name": "Roger", "pos": ["LB", "LM"], "ovr": 82},
            {"name": "Dinho", "pos": ["CDM", "CM"], "ovr": 80},
            {"name": "Goiano", "pos": ["CM"], "ovr": 74},
            {"name": "Carlos Miguel", "pos": ["CM", "CAM"], "ovr": 73},
            {"name": "Paulo Nunes", "pos": ["ST", "RW"], "ovr": 81},
            {"name": "Jardel", "pos": ["ST"], "ovr": 88},
            {"name": "Mário Jardel", "pos": ["ST"], "ovr": 80},
            {"name": "Émerson", "pos": ["CDM", "CM"], "ovr": 84},
            {"name": "Luís Carlos Goiano", "pos": ["RB"], "ovr": 70},
            {"name": "Catalino Rivarola", "pos": ["CB"], "ovr": 68},
        ],
    },
    # ---------- 18. ATLÉTICO-PR 2001 (Adriano / Kléberson - Brasileirão) ----------
    {
        "club": "Atlético-PR",
        "year": 2001,
        "label": "Atlético-PR 2001",
        "color": "#E2231A",
        "accent": "#000000",
        "players": [
            {"name": "Flávio", "pos": ["GK"], "ovr": 79},
            {"name": "Alessandro", "pos": ["RB"], "ovr": 75},
            {"name": "Igor", "pos": ["CB"], "ovr": 76},
            {"name": "Nem", "pos": ["CB"], "ovr": 73},
            {"name": "Cocito", "pos": ["LB"], "ovr": 72},
            {"name": "Kléberson", "pos": ["CM", "CDM"], "ovr": 82},
            {"name": "Alex Mineiro", "pos": ["ST", "RW"], "ovr": 80},
            {"name": "Lucas", "pos": ["CAM", "CM"], "ovr": 75},
            {"name": "Cocozza", "pos": ["LW", "LM"], "ovr": 70},
            {"name": "Adriano", "pos": ["ST"], "ovr": 86},
            {"name": "Ilan", "pos": ["ST"], "ovr": 75},
            {"name": "Bocanegra", "pos": ["CB"], "ovr": 72},
            {"name": "Sinha", "pos": ["CAM", "CM"], "ovr": 74},
            {"name": "Fabiano", "pos": ["RM", "RW"], "ovr": 68},
        ],
    },
    # ---------- 19. CORINTHIANS 1990 (Neto / Wladimir) ----------
    {
        "club": "Corinthians",
        "year": 1990,
        "label": "Corinthians 1990",
        "color": "#0A0A0A",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Ronaldo Giovanelli", "pos": ["GK"], "ovr": 80},
            {"name": "Wladimir", "pos": ["LB", "RB"], "ovr": 81},
            {"name": "Edivaldo", "pos": ["CB"], "ovr": 75},
            {"name": "Henrique", "pos": ["CB"], "ovr": 73},
            {"name": "Ezequias", "pos": ["LB"], "ovr": 70},
            {"name": "Mauro Silva", "pos": ["CDM", "CM"], "ovr": 86},
            {"name": "Wilson Mano", "pos": ["CM"], "ovr": 72},
            {"name": "Neto", "pos": ["CAM", "ST"], "ovr": 87},
            {"name": "Tupãzinho", "pos": ["ST", "CAM"], "ovr": 76},
            {"name": "Marcelo Djian", "pos": ["CAM", "CM"], "ovr": 75},
            {"name": "Viola", "pos": ["ST"], "ovr": 78},
            {"name": "Marquinhos", "pos": ["RW", "RM"], "ovr": 70},
            {"name": "Branco", "pos": ["LB"], "ovr": 70},
            {"name": "Paulinho McLaren", "pos": ["ST", "LW"], "ovr": 72},
        ],
    },
    # ---------- 20. CRUZEIRO 1997 (Libertadores - Donizete/Marcelo Ramos) ----------
    {
        "club": "Cruzeiro",
        "year": 1997,
        "label": "Cruzeiro 1997",
        "color": "#1B4FA0",
        "accent": "#FFD700",
        "players": [
            {"name": "Dida", "pos": ["GK"], "ovr": 86},
            {"name": "Vítor", "pos": ["RB"], "ovr": 75},
            {"name": "Wilson Gottardo", "pos": ["CB"], "ovr": 76},
            {"name": "Nonato", "pos": ["CB"], "ovr": 73},
            {"name": "Celso", "pos": ["LB"], "ovr": 72},
            {"name": "Ricardo Gomes", "pos": ["CDM", "CB"], "ovr": 78},
            {"name": "Ricardinho", "pos": ["CAM", "CM"], "ovr": 80},
            {"name": "Palhinha", "pos": ["ST"], "ovr": 76},
            {"name": "Donizete", "pos": ["ST", "CAM"], "ovr": 80},
            {"name": "Marcelo Ramos", "pos": ["ST"], "ovr": 82},
            {"name": "Bebeto", "pos": ["RM", "RW"], "ovr": 72},
            {"name": "Cleisson", "pos": ["LW", "LM"], "ovr": 70},
            {"name": "Ademir", "pos": ["CM"], "ovr": 70},
            {"name": "Sorín", "pos": ["LB"], "ovr": 76},
        ],
    },
    # ---------- 21. INTERNACIONAL 1979 (Falcão) ----------
    {
        "club": "Internacional",
        "year": 1979,
        "label": "Internacional 1979",
        "color": "#D40026",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Benítez", "pos": ["GK"], "ovr": 78},
            {"name": "Tonho", "pos": ["RB"], "ovr": 75},
            {"name": "Mauro Pastor", "pos": ["CB"], "ovr": 76},
            {"name": "Mauro Galvão", "pos": ["CB"], "ovr": 78},
            {"name": "Maciel", "pos": ["LB"], "ovr": 73},
            {"name": "Falcão", "pos": ["CM", "CDM"], "ovr": 91},
            {"name": "Batista", "pos": ["CDM", "CM"], "ovr": 80},
            {"name": "Bira", "pos": ["CAM", "CM"], "ovr": 75},
            {"name": "Caçapava", "pos": ["RW", "RM"], "ovr": 72},
            {"name": "Falcão Filho", "pos": ["ST"], "ovr": 70},
            {"name": "Chico Fraga", "pos": ["ST"], "ovr": 74},
            {"name": "Valdomiro", "pos": ["RW", "ST"], "ovr": 78},
            {"name": "Jair", "pos": ["LW", "LM"], "ovr": 72},
            {"name": "Carpegiani", "pos": ["CM"], "ovr": 76},
        ],
    },
    # ---------- 22. CORINTHIANS 2005 (Tevez/Mascherano - Brasileirão) ----------
    {
        "club": "Corinthians",
        "year": 2005,
        "label": "Corinthians 2005",
        "color": "#0A0A0A",
        "accent": "#FFD700",
        "players": [
            {"name": "Marcelo", "pos": ["GK"], "ovr": 79},
            {"name": "Coelho", "pos": ["RB"], "ovr": 73},
            {"name": "Sebá", "pos": ["CB"], "ovr": 75},
            {"name": "Marinho", "pos": ["CB"], "ovr": 73},
            {"name": "Gustavo Nery", "pos": ["LB"], "ovr": 75},
            {"name": "Javier Mascherano", "pos": ["CDM"], "ovr": 86},
            {"name": "Marcelo Mattos", "pos": ["CM", "CDM"], "ovr": 73},
            {"name": "Roger", "pos": ["CAM", "ST"], "ovr": 76},
            {"name": "Tevez", "pos": ["ST", "CAM"], "ovr": 89},
            {"name": "Nilmar", "pos": ["ST"], "ovr": 78},
            {"name": "Carlos Alberto", "pos": ["CAM", "CM"], "ovr": 76},
            {"name": "Rosinei", "pos": ["RW", "RM"], "ovr": 72},
            {"name": "Bobô", "pos": ["LW", "LM"], "ovr": 70},
            {"name": "Magrão", "pos": ["CDM"], "ovr": 68},
        ],
    },
    # ---------- 23. ATLÉTICO-MG 2021 (Galo Doido - Hulk/Diego Costa) ----------
    {
        "club": "Atlético-MG",
        "year": 2021,
        "label": "Atlético-MG 2021",
        "color": "#0A0A0A",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Everson", "pos": ["GK"], "ovr": 83},
            {"name": "Mariano", "pos": ["RB"], "ovr": 76},
            {"name": "Junior Alonso", "pos": ["CB"], "ovr": 80},
            {"name": "Réver", "pos": ["CB"], "ovr": 75},
            {"name": "Guilherme Arana", "pos": ["LB", "LM"], "ovr": 80},
            {"name": "Jair", "pos": ["CDM"], "ovr": 78},
            {"name": "Allan", "pos": ["CM", "CDM"], "ovr": 77},
            {"name": "Nacho Fernández", "pos": ["CAM", "CM"], "ovr": 82},
            {"name": "Savarino", "pos": ["RW", "CAM", "RM"], "ovr": 78},
            {"name": "Hulk", "pos": ["ST", "RW"], "ovr": 87},
            {"name": "Diego Costa", "pos": ["ST"], "ovr": 80},
            {"name": "Keno", "pos": ["LW", "LM"], "ovr": 78},
            {"name": "Vargas", "pos": ["ST", "CAM"], "ovr": 76},
            {"name": "Zaracho", "pos": ["CM", "CAM"], "ovr": 75},
        ],
    },
    # ---------- 24. FLAMENGO 2019 (Libertadores - Gabigol/Arrascaeta) ----------
    {
        "club": "Flamengo",
        "year": 2019,
        "label": "Flamengo 2019",
        "color": "#D40026",
        "accent": "#000000",
        "players": [
            {"name": "Diego Alves", "pos": ["GK"], "ovr": 84},
            {"name": "Rafinha", "pos": ["RB"], "ovr": 81},
            {"name": "Pablo Marí", "pos": ["CB"], "ovr": 80},
            {"name": "Rodrigo Caio", "pos": ["CB"], "ovr": 80},
            {"name": "Filipe Luís", "pos": ["LB"], "ovr": 84},
            {"name": "Willian Arão", "pos": ["CDM"], "ovr": 77},
            {"name": "Gerson", "pos": ["CM", "CAM"], "ovr": 82},
            {"name": "Giorgian de Arrascaeta", "pos": ["CAM", "CM"], "ovr": 86},
            {"name": "Bruno Henrique", "pos": ["LW", "ST"], "ovr": 84},
            {"name": "Gabigol", "pos": ["ST"], "ovr": 87},
            {"name": "Éverton Ribeiro", "pos": ["RW", "CAM", "RM"], "ovr": 83},
            {"name": "Diego", "pos": ["CAM", "CM"], "ovr": 78},
            {"name": "Pará", "pos": ["RB"], "ovr": 70},
            {"name": "Vitinho", "pos": ["LW", "RW"], "ovr": 72},
        ],
    },
    # ---------- 25. PALMEIRAS 1993 (Edmundo/Evair) ----------
    {
        "club": "Palmeiras",
        "year": 1993,
        "label": "Palmeiras 1993",
        "color": "#006437",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Sérgio", "pos": ["GK"], "ovr": 78},
            {"name": "Antônio Carlos", "pos": ["RB"], "ovr": 76},
            {"name": "Cléber", "pos": ["CB"], "ovr": 80},
            {"name": "Tonhão", "pos": ["CB"], "ovr": 76},
            {"name": "Roberto Carlos", "pos": ["LB", "LM"], "ovr": 90},
            {"name": "Mazinho", "pos": ["CDM", "CM"], "ovr": 80},
            {"name": "Zinho", "pos": ["CAM", "CM"], "ovr": 84},
            {"name": "César Sampaio", "pos": ["CM", "CDM"], "ovr": 80},
            {"name": "Edmundo", "pos": ["ST", "CAM"], "ovr": 84},
            {"name": "Evair", "pos": ["ST"], "ovr": 82},
            {"name": "Edílson", "pos": ["RW", "ST"], "ovr": 80},
            {"name": "Rivaldo", "pos": ["CAM", "ST", "LW"], "ovr": 88},
            {"name": "Müller", "pos": ["ST", "RW"], "ovr": 83},
            {"name": "Wilson Mano", "pos": ["CM"], "ovr": 68},
        ],
    },
    # ---------- 26. BOTAFOGO 1962 (Garrincha/Nilton Santos) ----------
    {
        "club": "Botafogo",
        "year": 1962,
        "label": "Botafogo 1962",
        "color": "#0A0A0A",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Manga", "pos": ["GK"], "ovr": 85},
            {"name": "Joel", "pos": ["RB"], "ovr": 76},
            {"name": "Nilton Santos", "pos": ["LB", "CB"], "ovr": 92},
            {"name": "Rildo", "pos": ["CB"], "ovr": 76},
            {"name": "Geraldo", "pos": ["CB"], "ovr": 72},
            {"name": "Didi", "pos": ["CM", "CAM"], "ovr": 93},
            {"name": "Zagallo", "pos": ["LW", "LM"], "ovr": 88},
            {"name": "Quarentinha", "pos": ["ST"], "ovr": 80},
            {"name": "Amarildo", "pos": ["ST", "CAM"], "ovr": 84},
            {"name": "Garrincha", "pos": ["RW", "RM"], "ovr": 97},
            {"name": "Amaral", "pos": ["CDM", "CM"], "ovr": 75},
            {"name": "Roberto Miranda", "pos": ["ST"], "ovr": 76},
            {"name": "Edson", "pos": ["CM"], "ovr": 70},
            {"name": "Paulo Valentim", "pos": ["ST"], "ovr": 74},
        ],
    },
    # ---------- 27. CRUZEIRO 1976 (Palhinha/Nelinho - Libertadores) ----------
    {
        "club": "Cruzeiro",
        "year": 1976,
        "label": "Cruzeiro 1976",
        "color": "#1B4FA0",
        "accent": "#FFFFFF",
        "players": [
            {"name": "Raul", "pos": ["GK"], "ovr": 78},
            {"name": "Nelinho", "pos": ["RB"], "ovr": 88},
            {"name": "Vanderlei Luxemburgo", "pos": ["CB"], "ovr": 70},
            {"name": "Morais", "pos": ["CB"], "ovr": 75},
            {"name": "Vanderlei", "pos": ["LB"], "ovr": 72},
            {"name": "Piazza", "pos": ["CDM", "CM", "CB"], "ovr": 85},
            {"name": "Zé Carlos", "pos": ["CM"], "ovr": 74},
            {"name": "Eduardo", "pos": ["CAM", "CM"], "ovr": 75},
            {"name": "Palhinha", "pos": ["ST"], "ovr": 82},
            {"name": "Joãozinho", "pos": ["RW", "RM"], "ovr": 76},
            {"name": "Jairzinho", "pos": ["RW", "ST"], "ovr": 90},
            {"name": "Roberto Batata", "pos": ["LW", "ST"], "ovr": 76},
            {"name": "Wilson Piazza", "pos": ["CDM"], "ovr": 78},
            {"name": "Zé Carlos II", "pos": ["LB"], "ovr": 65},
        ],
    },
    # ---------- 28. SÃO PAULO 1993 (Bi Libertadores - Müller/Cafu) ----------
    {
        "club": "São Paulo",
        "year": 1993,
        "label": "São Paulo 1993",
        "color": "#E2231A",
        "accent": "#000000",
        "players": [
            {"name": "Zetti", "pos": ["GK"], "ovr": 86},
            {"name": "Cafu", "pos": ["RB", "RM"], "ovr": 92},
            {"name": "Antônio Carlos", "pos": ["CB"], "ovr": 80},
            {"name": "Válber", "pos": ["CB"], "ovr": 76},
            {"name": "Leonardo", "pos": ["LB", "LM"], "ovr": 88},
            {"name": "Toninho Cerezo", "pos": ["CM", "CDM"], "ovr": 84},
            {"name": "Doriva", "pos": ["CDM", "CM"], "ovr": 76},
            {"name": "Dinho", "pos": ["CM", "CAM"], "ovr": 74},
            {"name": "Müller", "pos": ["RW", "ST"], "ovr": 86},
            {"name": "Palhinha", "pos": ["ST"], "ovr": 80},
            {"name": "Gilmar", "pos": ["LW", "ST"], "ovr": 74},
            {"name": "Juninho Paulista", "pos": ["CAM", "CM"], "ovr": 82},
            {"name": "Ronaldão", "pos": ["CB"], "ovr": 75},
            {"name": "Catê", "pos": ["ST"], "ovr": 68},
        ],
    },
]


def all_players_flat():
    """Return list of all players with squad metadata embedded."""
    out = []
    for sq in SQUADS:
        for p in sq["players"]:
            out.append({
                "id": f"{sq['club']}-{sq['year']}-{p['name']}",
                "name": p["name"],
                "positions": p["pos"],
                "ovr": p["ovr"],
                "club": sq["club"],
                "year": sq["year"],
                "squad_label": sq["label"],
                "color": sq["color"],
                "accent": sq["accent"],
            })
    return out


def get_squad_by_label(label):
    for sq in SQUADS:
        if sq["label"] == label:
            return sq
    return None


def all_squad_labels():
    return [sq["label"] for sq in SQUADS]
